### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by SaeedSheikhi** [liferay/liferay-js-toolkit#420]
## Your Environments
```
    "liferay-npm-bundler": "2.13.2",
    "liferay-npm-build-support": "2.13.2",
    "liferay-npm-bundler-loader-babel-loader": "2.13.2",
    "liferay-npm-bundler-loader-copy-loader": "2.13.2",
    "liferay-npm-bundler-loader-css-loader": "2.13.2",
    "liferay-npm-bundler-loader-json-loader": "2.13.2",
    "liferay-npm-bundler-loader-sass-loader": "2.13.2",
    "liferay-npm-bundler-loader-style-loader": "2.13.2",
```

## Expected Behavior

1- cloning https://github.com/izaera/liferay-js-toolkit-showcase/tree/loaders branch
2- run `npm install`
3- run `npm run start` and project boots up without error.
## Actual Behavior

script crashed on step 3 with some errors about path resolving, tested on windows and macos, results are the same.
## Error Stack

```shell
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:981:7)
    at runWebpackDevServer (/Users/saeedsheikhi/Desktop/liferay-js-toolkit-showcase/node_modules/liferay-npm-build-support/lib/scripts/start.js:113:46)
    at Object.exports.default (/Users/saeedsheikhi/Desktop/liferay-js-toolkit-showcase/node_modules/liferay-npm-build-support/lib/scripts/start.js:9:2)
    at Object.<anonymous> (/Users/saeedsheikhi/Desktop/liferay-js-toolkit-showcase/node_modules/liferay-npm-build-support/bin/lnbs-start.js:2:40)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! liferay-js-toolkit-showcase@1.0.0 start: `lnbs-start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the liferay-js-toolkit-showcase@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saeedsheikhi/.npm/_logs/2019-09-24T06_56_23_436Z-debug.log
 }
```

**Comment by MarcoPortillo** [comment]
Any solutions for this? I have same error when I run npm run start, I haven't edited anything, I just installed the portlet normally. My error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle infoserver-react@1.0.0~prestart: infoserver-react@1.0.0
6 info lifecycle infoserver-react@1.0.0~start: infoserver-react@1.0.0
7 verbose lifecycle infoserver-react@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle infoserver-react@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\A738782\OneDrive - Atos\Desktop\bis-portal-72\bis-workspace\modules\infoserver\infoserver-react\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_221\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\A738782\.jpm\windows\bin;C:\Users\A738782\AppData\Local\Microsoft\WindowsApps;C:\Users\A738782\AppData\Roaming\npm;C:\Users\A738782\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle infoserver-react@1.0.0~start: CWD: C:\Users\A738782\OneDrive - Atos\Desktop\bis-portal-72\bis-workspace\modules\infoserver\infoserver-react
10 silly lifecycle infoserver-react@1.0.0~start: Args: [ '/d /s /c', 'lnbs-start' ]
11 silly lifecycle infoserver-react@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle infoserver-react@1.0.0~start: Failed to exec start script
13 verbose stack Error: infoserver-react@1.0.0 start: `lnbs-start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid infoserver-react@1.0.0
15 verbose cwd C:\Users\A738782\OneDrive - Atos\Desktop\bis-portal-72\bis-workspace\modules\infoserver\infoserver-react
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error infoserver-react@1.0.0 start: `lnbs-start`
22 error Exit status 1
23 error Failed at the infoserver-react@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
I want to run the portlet as a normal react app while developing only the front-end for faster development, what to do? I want to only deploy when I finish.

**Comment by wsyski** [comment]
I could see the same problem with a freshly generated angular project
