### ISSUE TITLE
Angular Lazy modules are not lazy

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-js-toolkit#460]
I have tried to overcome my Angular performance problems I have described in issue #457 by implementing Angular modules lazy loading as described in:

https://angular.io/guide/lazy-loading-ngmodules

Unfortunately I have discovered that the angular lazy modules are not treated as lazy by the npm bundler. This is because the routing module is translated with the dependencies on the lazy modules in the Liferay.Loader.define statement, so the lazy modules are loaded at once. Everything works fine, except the performance since the lazy modules are becoming eager modules. I can provide you with a simple example if you need it.

**Comment by wsyski** [comment]
The actual code generated by npm bundler is:
loadChildren: () => Promise.resolve().then(() => require('./calendar-event-list-detail.module')).then(module => module.CalendarEventListDetailModule)

Maybe require('./calendar-event-list-detail.module')) could be replaced by Liferay.Loader.require?

**Comment by izaera** [comment]
The documentation you pasted (if I understand it correctly) says that you need to use async `import()` to lazily load modules:

```javascript
const routes: Routes = [
    { path: 'customer-list',
      loadChildren: () => import('./customers/customers.module').then(m => m.CustomersModule) }
    ];
```

That makes sense, because if you use the usual node `require()` there's no way to distinguish between asynchronous requests. In fact, node's `require()` is synchronous, so there's no way to make it work in the browser unless you have already loaded the dependency in advance.

So, the only things you need to make sure lazy loading works in Liferay are:

1) Make sure async `import()` ends up in the JS code inside your JAR file (i.e.: make sure nobody, whether it's babel, webpack, or any other tool, is transforming it to a *magic* `require` construct for example)
2) Make sure async `import()` is equivalent to `Liferay.Loader.require()`

Number 1 should be easy to get, I guess. It's a matter of tweaking the build before the bundler kicks in, I suppose, so that it finds imports unmodified.

Regarding number 2, we don't have any OOTB functionality for that, but I can think of two ways to achieve it:

1) the dirty way: just redefine `import()` before using it to make it call `Liferay.Loader.require` and return a `Promise`
2) the cleaner way: transpile async `import()` during build time to call `Liferay.Loader.require`.

**Comment by wsyski** [comment]
As I understand the only way to proceed now is to manipulate the resulting bundled code. Provided my module code in the case you decide to implement this in the future.
[lazy.zip](https://github.com/liferay/liferay-js-toolkit/files/3891674/lazy.zip)

**Comment by izaera** [comment]
@wsyski Thx :-). 

It's an interesting feature, so we may implement it in the future. Sadly we don't have infinite resources :-(

However, you wouldn't need to manipulate the resulting bundled code if you provide a "polyfill" for "import()" to redirect it to "Liferay.Loader.define". I'm assuming here that the "import" calls end up in the resulting JAR's JS files which I don't know if it is true...

**Comment by izaera** [comment]
Ah OK, looking at the ZIP now I see that the `import` call is in the .ts file and it already comes transpiled by `tsc` into a promise.

That makes it much more difficult unless we somehow feed the `.ts` version to the bundler as trying to converse the `Promise.resolve().then(` construct would be quite difficult.

How does webpack handle this? How does it make the require() calls coming from import() async? I guess it can't... :thinking:

**Comment by wsyski** [comment]
Please forget about my sample files I have sent you before. They were created with module:  "commonjs" in tsconfig.json. It turned out that even pure angular project with module: "commonjs" does not create lazy modules! Everything works fine but modules are not lazy. To get lazy modules working one has to set "module": "esnext" in tsconfig.json - even for pure angular project. I have created a pure angular project with lazy modules and then run:
yo liferay-js:adapt
It almost worked after the deployment to liferay. The main module loaded fine, but the links to the lazy modules did not work, since your adaptation module renames the lazy script names. I have attached the whole project to the case so you can try what happens yourself.
[lazy-modules.zip](https://github.com/liferay/liferay-js-toolkit/files/3907578/lazy-modules.zip)

**Comment by wsyski** [comment]
I have tried to compile my large angular project using "module": "esnext" setting. Unfortunately it did not work.

logger.js:28 liferay-amd-loader | 
 A require() call has failed but no failure handler was provided.
 Note that even if the call stack of this error trace looks like coming from the Liferay AMD Loader, it is not an error in the Loader what has caused it, but an error caused by the require() call.
 The reason why the Loader is in the stack trace is because it is printing the error so that it doesn't get lost.
 However, we recommend providing a failure handler in all require() calls to be able to recover from errors better and to avoid the appearance of this message.
 
 Some information about the require() call follows:
   · Require call id: 1 
   · Required modules: ["calendar-event-list@5.0.0/lib/index"] 
   · Missing modules: ["calendar-event-list@5.0.0/lib/index"] 
   · Stack trace of the require() call: 
        Error
            at e.value (http://localhost:6080/o/frontend-js-web/loader/loader.js:1:5898)
            at http://localhost:6080/web/arena/welcome:2669:30
            at args.<computed> (http://localhost:6080/o/frontend-js-web/liferay/aui_sandbox.js:31:28)
            at YUI._notify (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:1105:17)
            at YUI.handleLoader (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:1250:27)
            at Y.Loader._finish (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:8227:19)
            at Y.Loader._onSuccess (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:8276:14)
            at Y.Loader.complete (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:8515:24)
            at Y.Loader.onSuccess (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:8577:30)
            at Transaction._finish (http://localhost:6080/o/frontend-js-web/aui/aui/aui.js:4994:31) 
 Error: Load timeout for modules: calendar-event-list@5.0.0/lib/index
    at loader.js:487

**Comment by wsyski** [comment]
On the other hand a default project generated as:
yo liferay-js
works fine even with "module": "esnext" setting in tsconfig.json
I wonder if the npm bundler and amd loader support "esnext"? In the documentation I always see module: "commonjs" Maybe esnext is the correct way to support the lazy modules. Do you have any comment on this? It would be a very desired feature, where the bundle is quite large.

**Comment by wsyski** [comment]
Only esnext supports dynamic import:
https://github.com/microsoft/TypeScript/issues/24082

**Comment by izaera** [comment]
Sadly, we don't support esnext yet. The bundler expects CommonJS/ES5 files as input so anything outside of that will make it behave incorrectly.

With the new `loaders` feature there's a possibility that we can support on the fly transpilation of third party deps and make more magic happen, but we have not yet explored that possibility.

This is somewhat related to #261.

**Comment by wsyski** [comment]
Yes I understand that introducing the general support for esnext is a not straightforward, but in the adaptation approach we can already use esnext, and it almost works fine. The main module loaded fine, but the links to the lazy modules did not work, since your adaptation module renames the lazy script file names. I have attached the whole project to the case so you can try what happens yourself.

**Comment by wincent** [comment]
Going to do a mass-transfer of issues (including this one):

- **From:** https://github.com/liferay/liferay-js-toolkit/issues
- **To:** https://github.com/liferay/liferay-frontend-projects/issues

Note that many of the issues that we move may be stale, but we can close those once we've had time to review them. In the meantime, doing a bulk move makes is cheap and it will allow us to mark the liferay-js-toolkit repo as archived (read-only), which is an important final step in the consolidation process in order to avoid confusion.
