### ISSUE TITLE
Review parallel actions to avoid EMFILE errors in bundler 3

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#577]
Before we release, we should constrain all parallel processes as we did in bundler 2 to avoid EMFILE errors (especially in Windows machines).

**Comment by aggie2016** [comment]
I was able to produce an issue in `liferay-npm-bundler` that might be related in v2.18.5 and v3.0.0-alpha.1. The issue arises when building with this `package.json`:

The project itself was scaffolded using `yo liferay-js`:
```
{
	"name": "testing-liferay-react",
	"version": "1.0.0",
	"description": "Testing Liferay React Portlet",
	"browserslist": {
		"production": [
			">0.2%",
			"not dead",
			"not op_mini all",
			"ie >= 9"
		],
		"development": [
			"last 1 chrome version",
			"last 1 firefox version",
			"last 1 safari version",
			"ie >= 9"
		]
	},
	"devDependencies": {
		"@testing-library/jest-dom": "^4.2.4",
		"@testing-library/react": "^9.5.0",
		"@testing-library/user-event": "^7.2.1",
		"@types/color": "^3.0.1",
		"@types/jquery": "^3.3.35",
		"@types/node-sass": "^4.11.0",
		"@types/react": "^16.9.34",
		"@types/react-dom": "^16.9.6",
		"@types/react-table": "^7.0.16",
		"@types/styled-components": "^5.1.0",
		"@types/tinymce": "^4.5.24",
		"babel-cli": "6.26.0",
		"babel-preset-env": "1.7.0",
		"babel-preset-react": "6.24.1",
		"babel-loader": "7.1.5",
		"liferay-npm-bundler": "^2.18.5",
		"liferay-npm-build-support": "^2.18.5",
		"copy-webpack-plugin": "4.6.0",
		"css-loader": "^3.5.3",
		"file-loader": "^6.0.0",
		"node-sass": "^4.14.0",
		"source-map-loader": "^0.2.4",
		"style-loader": "^1.2.0",
		"ts-loader": "^7.0.1",
		"typescript": "^3.8.3",
		"webpack": "^4.29.6",
		"webpack-cli": "^3.3.0",
		"webpack-dev-server": "3.2.1",
		"webpack-strip-block": "^0.2.0"
	},
	"dependencies": {
		"@fortawesome/fontawesome-svg-core": "^1.2.28",
		"@fortawesome/free-solid-svg-icons": "^5.13.0",
		"@fortawesome/react-fontawesome": "^0.1.9",
		"@ionic/react": "^5.1.0",
		"@ionic/react-hooks": "0.0.6",
		"@tinymce/tinymce-react": "^3.6.0",
		"bootstrap": "^4.4.1",
		"color": "^3.1.2",
		"react": "^16.13.1",
		"react-app-polyfill": "^1.0.6",
		"react-bootstrap": "^1.0.1",
		"react-data-table-component": "^6.8.0",
		"react-dom": "^16.13.1",
		"react-dropzone": "^11.0.1",
		"react-router-dom": "^5.1.2",
		"react-scripts": "3.4.1",
		"react-table": "^7.0.4",
		"semantic-ui-css": "^2.4.1",
		"semantic-ui-react": "^0.88.2",
		"styled-components": "^5.1.0",
		"tinymce": "^5.2.2"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"translate": "lnbs-translate",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
	"portlet": {
		"com.liferay.portlet.display-category": "testing.react.portlet",
		"com.liferay.portlet.header-portlet-css": "/css/styles.css",
		"com.liferay.portlet.instanceable": true,
		"javax.portlet.name": "TestingReact",
		"javax.portlet.security-role-ref": "power-user,user",
		"javax.portlet.resource-bundle": "content.Language"
	},
	"main": "index.js"
}
```

The output of running `npm run build` is included below:
```
C:\sandbox\git\finding-bugs>npm run build

> finding-bugs@1.0.0 build C:\sandbox\git\finding-bugs
> babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler

src\index.js -> build\index.js

> finding-bugs@1.0.0 copy-assets C:\sandbox\git\finding-bugs
> lnbs-copy-assets

Project assets copied.


Error: EMFILE: too many open files, open 'C:\sandbox\git\testing-liferay-react\node_modules\babel-preset-liferay-standard\package.json'
    at Object.openSync (fs.js:458:3)
    at readFileSync (fs.js:360:35)
    at loadpkg (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:129:20)
    at loadAsFileSync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:94:19)
    at loadAsDirectorySync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:174:16)
    at loadNodeModulesSync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:186:25)
    at Function.resolveSync [as sync] (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:85:17)
    at Project.resolve (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:219:34)
    at Project.toolResolve (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:273:25)
    at Project.toolRequire (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:252:29)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! finding-bugs@1.0.0 build: `babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the finding-bugs@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aggie2016\AppData\Roaming\npm-cache\_logs\2020-05-26T20_38_56_916Z-debug.log

C:\sandbox\git\testing-liferay-react>liferay-npm-bundler --version
3.0.0-alpha.1
```

**Comment by aggie2016** [comment]
I was able to produce an issue in `liferay-npm-bundler` that might be related in v2.18.5 and v3.0.0-alpha.1. The issue arises when building with this `package.json`:

The project itself was scaffolded using `yo liferay-js`:
```
{
	"name": "testing-liferay-react",
	"version": "1.0.0",
	"description": "Testing Liferay React Portlet",
	"browserslist": {
		"production": [
			">0.2%",
			"not dead",
			"not op_mini all",
			"ie >= 9"
		],
		"development": [
			"last 1 chrome version",
			"last 1 firefox version",
			"last 1 safari version",
			"ie >= 9"
		]
	},
	"devDependencies": {
		"@testing-library/jest-dom": "^4.2.4",
		"@testing-library/react": "^9.5.0",
		"@testing-library/user-event": "^7.2.1",
		"@types/color": "^3.0.1",
		"@types/jquery": "^3.3.35",
		"@types/node-sass": "^4.11.0",
		"@types/react": "^16.9.34",
		"@types/react-dom": "^16.9.6",
		"@types/react-table": "^7.0.16",
		"@types/styled-components": "^5.1.0",
		"@types/tinymce": "^4.5.24",
		"babel-cli": "6.26.0",
		"babel-preset-env": "1.7.0",
		"babel-preset-react": "6.24.1",
		"babel-loader": "7.1.5",
		"liferay-npm-bundler": "^2.18.5",
		"liferay-npm-build-support": "^2.18.5",
		"copy-webpack-plugin": "4.6.0",
		"css-loader": "^3.5.3",
		"file-loader": "^6.0.0",
		"node-sass": "^4.14.0",
		"source-map-loader": "^0.2.4",
		"style-loader": "^1.2.0",
		"ts-loader": "^7.0.1",
		"typescript": "^3.8.3",
		"webpack": "^4.29.6",
		"webpack-cli": "^3.3.0",
		"webpack-dev-server": "3.2.1",
		"webpack-strip-block": "^0.2.0"
	},
	"dependencies": {
		"@fortawesome/fontawesome-svg-core": "^1.2.28",
		"@fortawesome/free-solid-svg-icons": "^5.13.0",
		"@fortawesome/react-fontawesome": "^0.1.9",
		"@ionic/react": "^5.1.0",
		"@ionic/react-hooks": "0.0.6",
		"@tinymce/tinymce-react": "^3.6.0",
		"bootstrap": "^4.4.1",
		"color": "^3.1.2",
		"react": "^16.13.1",
		"react-app-polyfill": "^1.0.6",
		"react-bootstrap": "^1.0.1",
		"react-data-table-component": "^6.8.0",
		"react-dom": "^16.13.1",
		"react-dropzone": "^11.0.1",
		"react-router-dom": "^5.1.2",
		"react-scripts": "3.4.1",
		"react-table": "^7.0.4",
		"semantic-ui-css": "^2.4.1",
		"semantic-ui-react": "^0.88.2",
		"styled-components": "^5.1.0",
		"tinymce": "^5.2.2"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"translate": "lnbs-translate",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
	"portlet": {
		"com.liferay.portlet.display-category": "testing.react.portlet",
		"com.liferay.portlet.header-portlet-css": "/css/styles.css",
		"com.liferay.portlet.instanceable": true,
		"javax.portlet.name": "TestingReact",
		"javax.portlet.security-role-ref": "power-user,user",
		"javax.portlet.resource-bundle": "content.Language"
	},
	"main": "index.js"
}
```

The output of running `npm run build` is included below:
```
C:\sandbox\git\testing-liferay-react>npm run build

> testing-liferay-react@1.0.0 build C:\sandbox\git\testing-liferay-react
> babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler

src\index.js -> build\index.js

> testing-liferay-react@1.0.0 copy-assets C:\sandbox\git\testing-liferay-react
> lnbs-copy-assets

Project assets copied.


Error: EMFILE: too many open files, open 'C:\sandbox\git\testing-liferay-react\node_modules\babel-preset-liferay-standard\package.json'
    at Object.openSync (fs.js:458:3)
    at readFileSync (fs.js:360:35)
    at loadpkg (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:129:20)
    at loadAsFileSync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:94:19)
    at loadAsDirectorySync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:174:16)
    at loadNodeModulesSync (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:186:25)
    at Function.resolveSync [as sync] (C:\sandbox\git\testing-liferay-react\node_modules\resolve\lib\sync.js:85:17)
    at Project.resolve (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:219:34)
    at Project.toolResolve (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:273:25)
    at Project.toolRequire (C:\sandbox\git\testing-liferay-react\node_modules\liferay-npm-build-tools-common\lib\project\index.js:252:29)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! finding-bugs@1.0.0 build: `babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the finding-bugs@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aggie2016\AppData\Roaming\npm-cache\_logs\2020-05-26T20_38_56_916Z-debug.log

C:\sandbox\git\testing-liferay-react>liferay-npm-bundler --version
3.0.0-alpha.1
```

**Comment by aggie2016** [comment]
After further review, this issue seems to have stemmed from the inclusion of `react-scripts` as a dependency. After moving this to `devDependencies` the issue seems to have resolved itself.

**Comment by izaera** [comment]
@aggie2016 this issue was intended for the new version we are developing. For 2.x series just use [this config setting](https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference#max-parallel-files).

**Comment by jwanner83** [comment]
Hey I have a question according to this problem. We currently run into the issue with the open files limit. After discovering this github issue I added the `max-parallel-files` rule to the `.npmbundlerrc` and it worked after setting the value to `48`. Unfortunately it now takes 23 minuets to build the portlet, which is of course logical. 
My question now is: is it foreseeable that the bundler will soon be upgraded to a stable version 3 with this problem solved?

**Comment by izaera** [comment]
@jwanner83 We don't have an estimation for bundler 3 release yet. 

Regarding your problem, because the build process changes completely (using webpack under the hood) it is probable that it will be solved, as the amount of processing and the way to do it is very different.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
