### ISSUE TITLE
System Settings/Instance Settings not Working in generator-liferay-js@2.18.5 in Portal 7.3

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-toolkit#594]
The System Settings/Instance Settings throw a null pointer exception for a React widget with sample features added.

1. yo liferay-js
1. Create a React Widget and accept the defaults to add sample content
1. Answer "no" to the local installation prompt
1. Build JAR and manually copy it to Docker container `docker cp my-react-project_1.0.0.jar docker_container_name:/opt/liferay/osgi/modules`
1. Open Control Panel -> Configuration -> System Settings -> Other -> category.my-react-project

Note: This also throws an error in a 7.3.2 GA3 Tomcat bundle as well

The Null pointer exception shown below is thrown, causing the page to not render:

```
2020-06-08 19:08:00.070 ERROR [http-nio-8080-exec-5][render_portlet_jsp:131] null
java.lang.NullPointerException
        at com.liferay.portal.configuration.metatype.definitions.annotations.internal.AnnotationsExtendedAttributeDefinition.getType(AnnotationsExtendedAttributeDefinition.java:107)
        at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMFormFieldType(ConfigurationModelToDDMFormConverter.java:260)
        at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMFormField(ConfigurationModelToDDMFormConverter.java:183)
        at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.addDDMFormFields(ConfigurationModelToDDMFormConverter.java:90)
        at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.addRequiredDDMFormFields(ConfigurationModelToDDMFormConverter.java:116)
        at com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverter.getDDMForm(ConfigurationModelToDDMFormConverter.java:71)
        at com.liferay.configuration.admin.web.internal.util.DDMFormRendererHelper.getDDMForm(DDMFormRendererHelper.java:109)
        at com.liferay.configuration.admin.web.internal.util.DDMFormRendererHelper.getDDMFormHTML(DDMFormRendererHelper.java:62)
        at com.liferay.configuration.admin.web.internal.portlet.action.EditConfigurationMVCRenderCommand.render(EditConfigurationMVCRenderCommand.java:177)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:274)
        at com.liferay.configuration.admin.web.internal.portlet.SystemSettingsPortlet.render(SystemSettingsPortlet.java:76)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
```
![Screenshot (746)](https://user-images.githubusercontent.com/7050434/84071565-eb3eae00-a99b-11ea-8382-4139329816f5.png)

The Tomcat log also prints this warning when the JAR is deployed:
```
08-Jun-2020 19:29:20.056 WARNING [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner] java.util.jar.Attributes.read Duplicate name in Manifest: Provide-Capability.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
08-Jun-2020 19:29:28.890 WARNING [fileinstall-C:/Users/liferay/opt/Liferay/bundles/liferay-ce-portal-tomcat-7.3.2-ga3/liferay-ce-portal-7.3.2-ga3/osgi/modules] java.util.jar.Attributes.read Duplicate name in Manifest: Provide-Capability.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
08-Jun-2020 19:29:28.892 WARNING [fileinstall-C:/Users/liferay/opt/Liferay/bundles/liferay-ce-portal-tomcat-7.3.2-ga3/liferay-ce-portal-7.3.2-ga3/osgi/modules] java.util.jar.Attributes.read Duplicate name in Manifest: Provide-Capability.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
```

**Comment by izaera** [comment]
This looks like there's a problem in the server side because it expects a Settings interface class, but we don't provide it as Pure JavaScript portlets are instantiated on the fly.

I will probably create a LPS to deal with this (once I have a clear view of what is happening and where it can be fixed).

**Comment by mwilliams2014** [comment]
I know it worked before, so it seems some functionality/logic was removed in newer versions. Unless the JS Portlet Extender app was removed by default in 7.3...

**Comment by izaera** [comment]
This seems to be caused by https://issues.liferay.com/browse/LPS-100991.

I will open a new LPS to ask for a fix, because the changes introduced in that LPS are incorrect.

**Comment by izaera** [comment]
I have created https://issues.liferay.com/browse/LPS-115476
